version: '2'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
    environment:
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_USERNAME=guest
volumes:
  rabbitmq_data:
    driver: local